apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canary-app
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
spec:
  ingressClassName: nginx
  rules:
    - host: canary.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: canary-app-stable
                port:
                  number: 80
